# This is a basic workflow to help you get started with Actions

name: Linting-code

on: push #action when someone do something when someone push something this will invoke tigger so this is events

jobs:      #different things that needs to be triggered once. jobs has certain steps
 linting-code:
    name: Lint incoming code changes
    runs-on: ubuntu-latest
    steps:
         - name: Checking out code
           uses: actions/checkout@v2
         
         - name: Run Linting-code
           uses: github/super-linter@v3
          
      
      
    
